name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: "1.8"

      - uses: actions/checkout@v2

      - name: JVM build
        run: ./gradlew app-chip8-desktop:distZip

      - uses: actions/upload-artifact@v2
        with:
          name: app-chip8-desktop
          path: app-chip8-desktop/build/distributions/app-chip8-desktop.zip
